Sage-CloudPlatform-Core-/Solutions/PlatformSamples/AspNetLab/Controllers/AzureCacheController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sage.Core.Cache;

namespace AspNetLab.Controllers
{
    public class AzureCacheController : BaseController
    {
        public AzureCacheController(ICache cache) : base(cache)
        {
            
        }

        //
        // GET: /AzureCacheTest/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SetCache(string txtName)
        {
            SageCache.SetCacheItem("SampleCacheValue", txtName);
            ViewBag.IsSaved = true;
            return View("Index");
        }

        public ActionResult GetCache(string txtName)
        {
            ViewBag.IsSaved = true;
            ViewBag.CachedValue = SageCache.GetCacheItem("SampleCacheValue");
            return View("Index");
        }

        public ActionResult RemoveCache()
        {
            SageCache.RemoveCacheItem("SampleCacheValue");
            ViewBag.IsSaved = false;
            ViewBag.CachedValue = null;
            return View("Index");
        }
	}
}

Sage-CloudPlatform-Core-/Solutions/PlatformSamples/AspNetLab/Views/AzureCache/Partials/_AddCache.cshtml
<p>Enter you name</p>
@using (Html.BeginForm("SetCache", "AzureCache"))
{
    @Html.TextBox("txtName")
    <input id="SubmitName" type="submit" value="Go" />
}

Sage-CloudPlatform-Core-/Solutions/PlatformSamples/AspNetLab/Views/AzureCache/Partials/_GetCache.cshtml
<p>
    Hello @ViewBag.CachedValue !! Click @Html.ActionLink("Here", "RemoveCache") to removed the cached value.
</p>

Sage-CloudPlatform-Core-/Solutions/PlatformSamples/AspNetLab/Views/AzureCache/Partials/_ShowSaveSuccess.cshtml
<p>
    We have saved your name in Cache. Click @Html.ActionLink("Here", "GetCache") to view the cached value.
</p>