Sage-CloudPlatform-Core-/Solutions/PlatformSamples/AspNetLab/Controllers/AzureBlobController.cs
using System;
using System.Linq;
using System.IO;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using AspNetLab.Models;
using Sage.Core.Cache;
using Sage.Core.Framework.Storage;
using CoreCommon = Sage.Core.Framework.Common;

namespace AspNetLab.Controllers
{
    public class AzureBlobController : BaseController
    {
        public AzureBlobController(ICache cache, IBlobStore blob, IVersionBlobStore versionBlob,
                                   IChunkBlobStore chunkBlob)
            : base(cache)
        {
            Blob = blob;
            VersionBlob = versionBlob;
            ChunkBlob = chunkBlob;
            DomainContext = GetDomainContext();
        }

        #region BlobStore usage sample

        /// <summary>
        /// Simple upload landing page
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Normal file upload
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Upload()
        {

            if (!ImageIsSelected(Request.Files))
            {
                ViewBag.HasUploadError = true;
                return View("Index");
            }

            string uniqueFileName = Request.Files[0].FileName.ToLower();

            Blob.Put(DomainContext, new StreamBlob { Content = Request.Files[0].InputStream, Name = uniqueFileName, Path = "sagelabs" });

            ViewBag.IsUploaded = true;
            ViewBag.HasUploadError = false;
            ViewBag.FileName = Request.Files[0].FileName;
            ViewBag.UniqueFileName = uniqueFileName;

            return View("Index");
        }

        /// <summary>
        /// Normal file download
        /// </summary>
        /// <param name="fileName"></param>
        /// <param name="uniqueFileName"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Download(string fileName, string uniqueFileName)
        {
            ViewBag.FileName = fileName;
            ViewBag.UniqueFileName = uniqueFileName;
            ViewBag.IsUploaded = true;
            ControllerContext.HttpContext.Response.CacheControl = "private";
            ControllerContext.HttpContext.Response.AppendHeader("content-disposition", "attachment; filename=\"" + fileName + "\"");
            ControllerContext.HttpContext.Response.ContentType = "application/force-download";
            ControllerContext.HttpContext.Response.BufferOutput = false;

            Stream ret = new MemoryStream();

            Blob.Get(DomainContext, new StreamBlob { Content = Response.OutputStream, Name = uniqueFileName, Path = "sagelabs" });

            ret.Position = 0;
            ret.CopyTo(Response.OutputStream);
            Response.Flush();

            return null;
        }

        /// <summary>
        /// Simple Delete
        /// </summary>
        /// <param name="fileName"></param>
        /// <param name="uniqueFileName"></param>
        /// <param name="isChunk"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Delete(string fileName, string uniqueFileName, bool isChunk)
        {
            ViewBag.FileName = fileName;
            ViewBag.IsUploaded = false;

            ViewBag.IsDeleted = Blob.Delete(DomainContext, new StreamBlob { Name = uniqueFileName, Path = "sagelabs" });

            return isChunk ? View("ChunkIndex") : View("Index");
        }


        #endregion

        #region VersionBlobStore usage sample

        /// <summary>
        /// Version upload landing page
        /// </summary>
        /// <returns></returns>
        public ActionResult VersionIndex()
        {
            return View();
        }

        /// <summary>
        /// Upload new version
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult UploadVersion()
        {

            if (!ImageIsSelected(Request.Files))
            {
                ViewBag.HasUploadError = true;
                return View("Index");
            }

            string uniqueFileName = Request.Files[0].FileName.ToLower();

            VersionBlob.Put(DomainContext, new StreamBlob { Content = Request.Files[0].InputStream, Name = uniqueFileName, Path = "sagelabs" });

            ViewBag.IsUploaded = true;
            ViewBag.HasUploadError = false;
            ViewBag.FileName = Request.Files[0].FileName;
            ViewBag.UniqueFileName = uniqueFileName;

            return View("VersionIndex");
        }

        /// <summary>
        /// Download a specific version
        /// </summary>
        /// <param name="fileName"></param>
        /// <param name="uniqueFileName"></param>
        /// <param name="versionNumber"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DownloadVersion(string fileName, string uniqueFileName, int versionNumber)
        {
            ViewBag.FileName = fileName;
            ViewBag.UniqueFileName = uniqueFileName;
            ViewBag.IsUploaded = true;



            ControllerContext.HttpContext.Response.CacheControl = "private";
            ControllerContext.HttpContext.Response.AppendHeader("content-disposition",
                                                                "attachment; filename=\"" + fileName + "\"");
            ControllerContext.HttpContext.Response.ContentType = "application/force-download";
            ControllerContext.HttpContext.Response.BufferOutput = false;

            Stream ret = new MemoryStream();
            var versionList = VersionBlob.GetVersionInfo(DomainContext, new StreamBlob { Name = uniqueFileName, Path = "sagelabs" });
            var model = new VersionModel(versionList, fileName, uniqueFileName);
            var snapshot = model.VersionInfos.SingleOrDefault(x => x.VersionNumber == versionNumber).SnapshotDateTime;

            VersionBlob.Get(DomainContext,
                            new VersionBlobData<Stream>
                            {
                                BaseBlobData =
                                    new StreamBlob
                                    {
                                        Content = Response.OutputStream,
                                        Name = uniqueFileName,
                                        Path = "sagelabs"
                                    },
                                SnapshotDateTime = snapshot
                            });

            ret.Position = 0;
            ret.CopyTo(Response.OutputStream);
            Response.Flush();

            return null;
        }

        /// <summary>
        /// Get all versions of a file.
        /// </summary>
        /// <param name="fileName"></param>
        /// <param name="uniqueFileName"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GetAllVersions(string fileName, string uniqueFileName)
        {
            ViewBag.FileName = fileName;

            var versionList = VersionBlob.GetVersionInfo(DomainContext, new StreamBlob { Name = uniqueFileName, Path = "sagelabs" });

            var model = new VersionModel(versionList, fileName, uniqueFileName);
            ViewBag.IsUploaded = true;
            ViewBag.HasUploadError = false;
            ViewBag.VersionListed = true;
            ViewBag.UniqueFileName = uniqueFileName;

            return View("VersionIndex", model);
        }

        /// <summary>
        /// Delete a specific version
        /// </summary>
        /// <param name="fileName"></param>
        /// <param name="uniqueFileName"></param>
        /// <param name="versionNumber"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult DeleteVersion(string fileName, string uniqueFileName, int versionNumber)
        {
            ViewBag.FileName = fileName;
            ViewBag.UniqueFileName = uniqueFileName;
            ViewBag.IsUploaded = true;
            ViewBag.HasUploadError = false;
            ViewBag.VersionListed = true;

            var list = VersionBlob.GetVersionInfo(DomainContext, new StreamBlob { Name = uniqueFileName, Path = "sagelabs" });
            var model = new VersionModel(list, fileName, uniqueFileName);
            var snapshot = model.VersionInfos.SingleOrDefault(x => x.VersionNumber == versionNumber).SnapshotDateTime;

            VersionBlob.Delete(DomainContext,
                               new VersionBlobData<Stream>
                               {
                                   BaseBlobData =
                                       new StreamBlob
                                       {
                                           Content = Response.OutputStream,
                                           Name = uniqueFileName,
                                           Path = "sagelabs"
                                       },
                                   SnapshotDateTime = snapshot
                               });

            list = VersionBlob.GetVersionInfo(DomainContext, new StreamBlob { Name = uniqueFileName, Path = "sagelabs" });
            model = new VersionModel(list, fileName, uniqueFileName);
            return View("VersionIndex", model);
        }


        #endregion

        #region ChunkBlobStore usage sample

        /// <summary>
        /// Chunk upload landing page
        /// </summary>
        /// <param name="fileName"></param>
        /// <returns></returns>
        public ActionResult ChunkIndex(string fileName = null)
        {
            if (!string.IsNullOrEmpty(fileName))
            {
                ViewBag.IsUploaded = true;
                ViewBag.HasUploadError = false;
                ViewBag.IsChunkUpload = true;
                ViewBag.FileName = fileName.ToLower();
                ViewBag.UniqueFileName = fileName.ToLower();
            }

            return View();
        }

        /// <summary>

Sage-CloudPlatform-Core-/Solutions/PlatformSamples/AspNetLab/Views/AzureBlob/ChunkIndex.cshtml
@using AspNetLab.Helpers

@{
    ViewBag.Title = "Index";
}
<script src="~/Scripts/Plupload/plupload.js"></script>
<script src="~/Scripts/Plupload/jquery.ui.plupload/jquery.ui.plupload.js"></script>
<script src="@Url.Content("~/Scripts/Plupload/jquery.ui.plupload/jquery.ui.plupload.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Plupload/plupload.html4.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Plupload/plupload.html5.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Plupload/plupload.flash.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Plupload/Unminified/plupload.silverlight.js")" type="text/javascript"></script>
<link href="@Url.Content("~/Scripts/Plupload/jquery.ui.plupload.css")" rel="stylesheet" type="text/css" />

<p><b>Chunk Blob Test</b></p>
<div>
    @if (ViewBag.IsUploaded == null || !ViewBag.IsUploaded)
    {
        @Html.Partial("Partials/_UploadChunk")
        if (ViewBag.HasUploadError != null && ViewBag.HasUploadError == true)
        {
            @Html.Partial("Partials/_UploadError")
        }
        if (ViewBag.IsDeleted != null)
        {
            @(ViewBag.IsDeleted == true ? Html.Partial("Partials/_ShowDeleteSuccess") : Html.Partial("Partials/_ShowDeleteError"))
        }
    }
    else if (ViewBag.IsUploaded == true)
    {
        @Html.Partial("Partials/_DownloadFile")        
    }
</div>

@Html.MarkDown("ChunkBlobStore_Index")

Sage-CloudPlatform-Core-/Solutions/PlatformSamples/AspNetLab/Views/AzureBlob/Index.cshtml
@using AspNetLab.Helpers

@{
    ViewBag.Title = "Index";
}

<p><b>Blob Test</b></p>
<div>
    @if (ViewBag.IsUploaded == null || !ViewBag.IsUploaded)
    {
        @Html.Partial("Partials/_UploadFile")
        if (ViewBag.HasUploadError != null && ViewBag.HasUploadError == true)
        {
            @Html.Partial("Partials/_UploadError")
        }
        if (ViewBag.IsDeleted != null)
        {
            @(ViewBag.IsDeleted == true ? Html.Partial("Partials/_ShowDeleteSuccess") : Html.Partial("Partials/_ShowDeleteError"))
        }
    }
    else if (ViewBag.IsUploaded == true)
    {
        @Html.Partial("Partials/_DownloadFile")        
    }
</div>

@Html.MarkDown("AzureBlob_Index")

Sage-CloudPlatform-Core-/Solutions/PlatformSamples/AspNetLab/Views/AzureBlob/VersionIndex.cshtml
@using AspNetLab.Helpers

@{
    ViewBag.Title = "Index";
     var uniqueFileName = @ViewBag.UniqueFileName;
     var fileName = @ViewBag.FileName;
    ViewBag.IsVersion = true;
}
@model AspNetLab.Models.VersionModel
<p><b>Version Blob Test</b></p>
<div>
    @Html.Partial("Partials/_UploadFile")
    @if (ViewBag.IsUploaded == null || !ViewBag.IsUploaded)
    {
        if (ViewBag.HasUploadError != null && ViewBag.HasUploadError == true)
        {
            @Html.Partial("Partials/_UploadError")
        }
        if (ViewBag.IsDeleted != null)
        {
            @(ViewBag.IsDeleted == true ? Html.Partial("Partials/_ShowDeleteSuccess") : Html.Partial("Partials/_ShowDeleteError"))
        }
    }
    else if (ViewBag.IsUploaded == true)
    {
        @Html.Partial("Partials/_DownloadFile")
        if (ViewBag.VersionListed != null && ViewBag.VersionListed == true)
        {
           @Html.Partial("Partials/_VersionList", Model) 
        }
        else
        {
            using (Html.BeginForm("GetAllVersions", "AzureBlob"))
            {
                <p>Get Version @ViewBag.FileName 

                @Html.Hidden("fileName")
                @Html.Hidden("uniqueFileName")
                <input id="GetVersions" type="submit" value="GetVersions" /></p>

            }
        }  
    }
</div>

@Html.MarkDown("VersionBlobStore_Index")